config/routes.rb
RailsStaticPages::Application.routes.draw do

  

  root 'pages#home'
  get "/about",   to: "pages#about"
  get "/pricing", to: "pages#pricing"
  get "/contact", to: "pages#contact"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def pricing
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    generic_title = "Rails Sorta Static Pages"
    if page_title
      "#{page_title} | #{generic_title}"
    else
      generic_title
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<header>

  <h1 class="header-title">Rails Sorta Static Pages</h1>

  <nav class="nav-bar">
    <ul class="nav pull-center">
      <li><%= link_to "Home",    root_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Pricing", pricing_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

<%= render "layouts/header" %>
<%= yield %>

</div>

</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, full_title('About')) %>
<h1>About</h1>

<p>
Bicycle rights viral try-hard normcore letterpress craft beer. Bicycle
rights cred put a bird on it, Schlitz cray occupy shabby chic keffiyeh
Pitchfork art party umami pickled. Cray deep v McSweeney's literally.
Flexitarian gastropub hoodie, fixie irony pug PBR vegan. 8-bit sriracha
semiotics, Williamsburg Blue Bottle fashion axe retro gentrify crucifix. Pug
Pitchfork polaroid before they sold out freegan. Church-key iPhone occupy,
tote bag yr dreamcatcher Odd Future four loko letterpress mlkshk Bushwick
viral small batch.
</p>
<p>
Fap forage asymmetrical beard cardigan Schlitz, biodiesel American Apparel
artisan ugh. Sustainable plaid Blue Bottle, try-hard cred letterpress banjo.
Synth church-key tote bag, viral raw denim tofu chia squid Wes Anderson
leggings normcore. Bicycle rights beard Helvetica, Etsy plaid seitan tofu
Portland fingerstache mustache hella synth. Shoreditch YOLO ennui swag put a
bird on it. Stumptown Tonx cred VHS, fixie scenester mumblecore artisan XOXO
chambray forage hoodie authentic. Brooklyn mumblecore viral High Life synth
distillery plaid, Wes Anderson food truck dreamcatcher twee iPhone beard
Carles Intelligentsia.
</p>
<p>
Kickstarter lomo American Apparel Neutra, Thundercats sriracha Tonx selvage
shabby chic Tumblr brunch Portland pour-over. Raw denim Cosby sweater
distillery, Helvetica hoodie butcher bitters letterpress Austin quinoa
before they sold out. Tousled selvage meggings, DIY Austin pug drinking
vinegar Echo Park four loko lomo fashion axe scenester irony. Roof party
gastropub you probably haven't heard of them, actually drinking vinegar
biodiesel freegan Carles ethnic. Mixtape Williamsburg small batch Vice
PBR&B, keffiyeh freegan pug single-origin coffee ugh ethical direct trade
narwhal irony Shoreditch. Ethnic lomo photo booth, you probably haven't
heard of them mlkshk chia selvage salvia meh banjo before they sold out
church-key Schlitz leggings Shoreditch. Schlitz synth readymade kitsch.
</p>
<p>
Direct trade Marfa trust fund, letterpress VHS Odd Future artisan actually
McSweeney's umami kogi paleo. Seitan Brooklyn you probably haven't heard of
them roof party Intelligentsia distillery. Pork belly fap gentrify drinking
vinegar try-hard, tote bag VHS bitters quinoa post-ironic. Direct trade
Thundercats squid, 90's VHS +1 semiotics stumptown freegan McSweeney's
letterpress cred. Kitsch hashtag mixtape church-key Godard. Next level
scenester American Apparel crucifix, literally salvia gluten-free iPhone
vinyl narwhal. Pour-over retro Helvetica pop-up Pinterest.
</p>

app/views/pages/contact.html.erb
<% provide(:title, full_title('Contact')) %>
<h1>Contact</h1>

<p>
Bicycle rights viral try-hard normcore letterpress craft beer. Bicycle
rights cred put a bird on it, Schlitz cray occupy shabby chic keffiyeh
Pitchfork art party umami pickled. Cray deep v McSweeney's literally.
Flexitarian gastropub hoodie, fixie irony pug PBR vegan. 8-bit sriracha
semiotics, Williamsburg Blue Bottle fashion axe retro gentrify crucifix. Pug
Pitchfork polaroid before they sold out freegan. Church-key iPhone occupy,
tote bag yr dreamcatcher Odd Future four loko letterpress mlkshk Bushwick
viral small batch.
</p>
<p>
Fap forage asymmetrical beard cardigan Schlitz, biodiesel American Apparel
artisan ugh. Sustainable plaid Blue Bottle, try-hard cred letterpress banjo.
Synth church-key tote bag, viral raw denim tofu chia squid Wes Anderson
leggings normcore. Bicycle rights beard Helvetica, Etsy plaid seitan tofu
Portland fingerstache mustache hella synth. Shoreditch YOLO ennui swag put a
bird on it. Stumptown Tonx cred VHS, fixie scenester mumblecore artisan XOXO
chambray forage hoodie authentic. Brooklyn mumblecore viral High Life synth
distillery plaid, Wes Anderson food truck dreamcatcher twee iPhone beard
Carles Intelligentsia.
</p>
<p>
Kickstarter lomo American Apparel Neutra, Thundercats sriracha Tonx selvage
shabby chic Tumblr brunch Portland pour-over. Raw denim Cosby sweater
distillery, Helvetica hoodie butcher bitters letterpress Austin quinoa
before they sold out. Tousled selvage meggings, DIY Austin pug drinking
vinegar Echo Park four loko lomo fashion axe scenester irony. Roof party
gastropub you probably haven't heard of them, actually drinking vinegar
biodiesel freegan Carles ethnic. Mixtape Williamsburg small batch Vice
PBR&B, keffiyeh freegan pug single-origin coffee ugh ethical direct trade
narwhal irony Shoreditch. Ethnic lomo photo booth, you probably haven't
heard of them mlkshk chia selvage salvia meh banjo before they sold out
church-key Schlitz leggings Shoreditch. Schlitz synth readymade kitsch.
</p>
<p>
Direct trade Marfa trust fund, letterpress VHS Odd Future artisan actually
McSweeney's umami kogi paleo. Seitan Brooklyn you probably haven't heard of
them roof party Intelligentsia distillery. Pork belly fap gentrify drinking
vinegar try-hard, tote bag VHS bitters quinoa post-ironic. Direct trade
Thundercats squid, 90's VHS +1 semiotics stumptown freegan McSweeney's
letterpress cred. Kitsch hashtag mixtape church-key Godard. Next level
scenester American Apparel crucifix, literally salvia gluten-free iPhone
vinyl narwhal. Pour-over retro Helvetica pop-up Pinterest.
</p>

app/views/pages/home.html.erb
<% provide(:title, full_title('Home')) %>
<h1>Home</h1>

<p>
Bicycle rights viral try-hard normcore letterpress craft beer. Bicycle
rights cred put a bird on it, Schlitz cray occupy shabby chic keffiyeh
Pitchfork art party umami pickled. Cray deep v McSweeney's literally.
Flexitarian gastropub hoodie, fixie irony pug PBR vegan. 8-bit sriracha
semiotics, Williamsburg Blue Bottle fashion axe retro gentrify crucifix. Pug
Pitchfork polaroid before they sold out freegan. Church-key iPhone occupy,
tote bag yr dreamcatcher Odd Future four loko letterpress mlkshk Bushwick
viral small batch.
</p>
<p>
Fap forage asymmetrical beard cardigan Schlitz, biodiesel American Apparel
artisan ugh. Sustainable plaid Blue Bottle, try-hard cred letterpress banjo.
Synth church-key tote bag, viral raw denim tofu chia squid Wes Anderson
leggings normcore. Bicycle rights beard Helvetica, Etsy plaid seitan tofu
Portland fingerstache mustache hella synth. Shoreditch YOLO ennui swag put a
bird on it. Stumptown Tonx cred VHS, fixie scenester mumblecore artisan XOXO
chambray forage hoodie authentic. Brooklyn mumblecore viral High Life synth
distillery plaid, Wes Anderson food truck dreamcatcher twee iPhone beard
Carles Intelligentsia.
</p>
<p>
Kickstarter lomo American Apparel Neutra, Thundercats sriracha Tonx selvage
shabby chic Tumblr brunch Portland pour-over. Raw denim Cosby sweater
distillery, Helvetica hoodie butcher bitters letterpress Austin quinoa
before they sold out. Tousled selvage meggings, DIY Austin pug drinking
vinegar Echo Park four loko lomo fashion axe scenester irony. Roof party
gastropub you probably haven't heard of them, actually drinking vinegar
biodiesel freegan Carles ethnic. Mixtape Williamsburg small batch Vice
PBR&B, keffiyeh freegan pug single-origin coffee ugh ethical direct trade
narwhal irony Shoreditch. Ethnic lomo photo booth, you probably haven't
heard of them mlkshk chia selvage salvia meh banjo before they sold out
church-key Schlitz leggings Shoreditch. Schlitz synth readymade kitsch.
</p>
<p>
Direct trade Marfa trust fund, letterpress VHS Odd Future artisan actually
McSweeney's umami kogi paleo. Seitan Brooklyn you probably haven't heard of
them roof party Intelligentsia distillery. Pork belly fap gentrify drinking
vinegar try-hard, tote bag VHS bitters quinoa post-ironic. Direct trade
Thundercats squid, 90's VHS +1 semiotics stumptown freegan McSweeney's
letterpress cred. Kitsch hashtag mixtape church-key Godard. Next level
scenester American Apparel crucifix, literally salvia gluten-free iPhone
vinyl narwhal. Pour-over retro Helvetica pop-up Pinterest.
</p>

app/views/pages/pricing.html.erb
<% provide(:title, full_title('Pricing')) %>
<h1>Pricing</h1>

<p>
Bicycle rights viral try-hard normcore letterpress craft beer. Bicycle
rights cred put a bird on it, Schlitz cray occupy shabby chic keffiyeh
Pitchfork art party umami pickled. Cray deep v McSweeney's literally.
Flexitarian gastropub hoodie, fixie irony pug PBR vegan. 8-bit sriracha
semiotics, Williamsburg Blue Bottle fashion axe retro gentrify crucifix. Pug
Pitchfork polaroid before they sold out freegan. Church-key iPhone occupy,
tote bag yr dreamcatcher Odd Future four loko letterpress mlkshk Bushwick
viral small batch.
</p>
<p>
Fap forage asymmetrical beard cardigan Schlitz, biodiesel American Apparel
artisan ugh. Sustainable plaid Blue Bottle, try-hard cred letterpress banjo.
Synth church-key tote bag, viral raw denim tofu chia squid Wes Anderson
leggings normcore. Bicycle rights beard Helvetica, Etsy plaid seitan tofu
Portland fingerstache mustache hella synth. Shoreditch YOLO ennui swag put a
bird on it. Stumptown Tonx cred VHS, fixie scenester mumblecore artisan XOXO
chambray forage hoodie authentic. Brooklyn mumblecore viral High Life synth
distillery plaid, Wes Anderson food truck dreamcatcher twee iPhone beard
Carles Intelligentsia.
</p>
<p>
Kickstarter lomo American Apparel Neutra, Thundercats sriracha Tonx selvage
shabby chic Tumblr brunch Portland pour-over. Raw denim Cosby sweater
distillery, Helvetica hoodie butcher bitters letterpress Austin quinoa
before they sold out. Tousled selvage meggings, DIY Austin pug drinking
vinegar Echo Park four loko lomo fashion axe scenester irony. Roof party
gastropub you probably haven't heard of them, actually drinking vinegar
biodiesel freegan Carles ethnic. Mixtape Williamsburg small batch Vice
PBR&B, keffiyeh freegan pug single-origin coffee ugh ethical direct trade
narwhal irony Shoreditch. Ethnic lomo photo booth, you probably haven't
heard of them mlkshk chia selvage salvia meh banjo before they sold out
church-key Schlitz leggings Shoreditch. Schlitz synth readymade kitsch.
</p>
<p>
Direct trade Marfa trust fund, letterpress VHS Odd Future artisan actually
McSweeney's umami kogi paleo. Seitan Brooklyn you probably haven't heard of
them roof party Intelligentsia distillery. Pork belly fap gentrify drinking
vinegar try-hard, tote bag VHS bitters quinoa post-ironic. Direct trade
Thundercats squid, 90's VHS +1 semiotics stumptown freegan McSweeney's
letterpress cred. Kitsch hashtag mixtape church-key Godard. Next level
scenester American Apparel crucifix, literally salvia gluten-free iPhone
vinyl narwhal. Pour-over retro Helvetica pop-up Pinterest.
</p>